repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: debug-statements

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        types: [python]
        args: [--profile=black, --line-length=120]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
    -   id: ruff
        args: [--fix, --line-length=120]
        types_or: [python, pyi]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        name: mypy (types only)
        additional_dependencies: [types-setuptools]
        args: [--config-file=mypy.ini]
        types: [python]
        # Only check files that are staged for commit
        stages: [commit]
        # Don't fail the commit if there are type errors
        verbose: true
        exclude: ^tests/
